### ISSUE TITLE
allow React.ReactNode children, and iterate through to find TextNodes to highlight

### ISSUE THREAD

**Issue by daveyjones** [chadlavi/react-highlighter-ts#1]
Thanks for the great library! In my current use case, I need to highlight text within arbitrary HTML. This is what I have, but it doesn't seem to work:

```
<Highlight search={props.search}>
  <div dangerouslySetInnerHTML={{__html: props.data.content}} />
</Highlight>
```

I also tried something a little simpler, but it's also not working.

```
<Highlight search={props.search}>
  <div>{props.search}</div>
</Highlight>
```

Is there currently a way to do this?

**Comment by chadlavi** [comment]
Hi @daveyjones, thanks for getting in touch!

There isn't currently a way to do that, because Highlight's children <a href="https://github.com/chadlavi/react-highlighter-ts/blob/0f8da396a78294f3c85d3b7f6be10e157f3dc0b0/lib/highlight.model.ts#L38">must consist of a string</a>. This is a limitation inherited from the original non-TypeScript react-highlighter library. In creating this TypeScript implementation, I didn't change any of the functionality.

However, this is a not-insurmountable problem! It would actually be convenient for my use cases as well if Highlight accepted `ReactNode` children like any normal React component, then iterated through to find leaf text nodes that match the search pattern and highlighted them.

I'm not sure when I can take a look at this, but this is a good one. I'll see when I can fit this in.

**Comment by chadlavi** [comment]
@daveyjones give version `2.0.0` a go, that should fix this.

**Comment by daveyjones** [comment]
@chadlavi Awesome! Thanks!
